/** Java reproducer scenarios offered by the UI (feat-007 / feat-011 / feat-028). */
export type JavaScenario =
  | "lock-contention"
  | "deadlock"
  | "thread-pool-exhaustion";

/** Clamp the requested thread/worker count into a sane range (>= 2). */
function normalizeCount(count: number): number {
  if (!Number.isFinite(count)) return 2;
  return Math.min(64, Math.max(2, Math.trunc(count)));
}

export function classNameFor(scenario: JavaScenario): string {
  switch (scenario) {
    case "deadlock":
      return "DeadlockCycle";
    case "thread-pool-exhaustion":
      return "ThreadPoolExhaustion";
    default:
      return "LockContention";
  }
}

/**
 * Generate a runnable Java reproducer for a thread problem scenario.
 * Port of the former Rust/WASM `generateJava` (moved in feat-011 to shrink WASM).
 */
export function generateJava(scenario: JavaScenario, count: number): string {
  const n = normalizeCount(count);
  switch (scenario) {
    case "deadlock":
      return generateDeadlock(n);
    case "thread-pool-exhaustion":
      return generateThreadPoolExhaustion(n);
    default:
      return generateLockContention(n);
  }
}

function generateLockContention(workers: number): string {
  const nMinus1 = workers - 1;
  return `// Auto-generated by jblock: lock-contention reproducer.
// One thread holds LOCK forever; the other ${nMinus1} block waiting to enter it.
// Capture with: jstack <pid>  (or ThreadMXBean#dumpAllThreads)
public class LockContention {
    private static final Object LOCK = new Object();

    public static void main(String[] args) {
        final int workers = ${workers};
        for (int i = 0; i < workers; i++) {
            final int id = i;
            Thread t = new Thread(() -> {
                synchronized (LOCK) {
                    System.out.println("worker-" + id + " acquired LOCK");
                    // Hold the monitor so the remaining workers stay BLOCKED.
                    while (true) {
                        try {
                            Thread.sleep(Long.MAX_VALUE);
                        } catch (InterruptedException e) {
                            Thread.currentThread().interrupt();
                            return;
                        }
                    }
                }
            }, "worker-" + i);
            t.start();
        }
    }
}
`;
}

function generateDeadlock(threads: number): string {
  return `// Auto-generated by jblock: deadlock-cycle reproducer.
// ${threads} threads and ${threads} locks form a circular wait: thread i holds lock i and
// blocks acquiring lock (i+1) % ${threads}, closing a deadlock cycle.
// Capture with: jstack <pid>  (jstack also prints "Found one Java-level deadlock").
public class DeadlockCycle {
    public static void main(String[] args) {
        final int n = ${threads};
        final Object[] locks = new Object[n];
        for (int i = 0; i < n; i++) {
            locks[i] = new Object();
        }
        for (int i = 0; i < n; i++) {
            final int id = i;
            final Object first = locks[i];
            final Object second = locks[(i + 1) % n];
            Thread t = new Thread(() -> {
                synchronized (first) {
                    System.out.println("thread-" + id + " locked " + id);
                    try {
                        Thread.sleep(200);
                    } catch (InterruptedException e) {
                        Thread.currentThread().interrupt();
                        return;
                    }
                    synchronized (second) {
                        System.out.println("thread-" + id + " locked next");
                    }
                }
            }, "deadlock-" + i);
            t.start();
        }
    }
}
`;
}

function generateThreadPoolExhaustion(workers: number): string {
  return `// Auto-generated by jblock: thread-pool-exhaustion reproducer.
// A fixed pool of ${workers} workers all enter the same monitor; one holds it while
// sleeping and the rest stay BLOCKED — no idle getTask worker remains.
// Capture with: jstack <pid>
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class ThreadPoolExhaustion {
    private static final Object LOCK = new Object();

    public static void main(String[] args) throws Exception {
        final int workers = ${workers};
        final ExecutorService pool = Executors.newFixedThreadPool(workers);
        final CountDownLatch entered = new CountDownLatch(workers);
        for (int i = 0; i < workers; i++) {
            pool.submit(() -> {
                entered.countDown();
                synchronized (LOCK) {
                    try {
                        Thread.sleep(Long.MAX_VALUE);
                    } catch (InterruptedException e) {
                        Thread.currentThread().interrupt();
                    }
                }
            });
        }
        entered.await();
        // Keep the JVM alive so jstack can capture the stuck pool.
        Thread.sleep(Long.MAX_VALUE);
    }
}
`;
}
