/** Java reproducer scenarios offered by the UI (feat-007 / feat-011 / feat-028+). */
export type JavaScenario =
  | "lock-contention"
  | "deadlock"
  | "thread-pool-exhaustion"
  | "sync-io-hotspot"
  | "dangerous-hot-lock";

/** Clamp the requested thread/worker count into a sane range (>= 2). */
function normalizeCount(count: number): number {
  if (!Number.isFinite(count)) return 2;
  return Math.min(64, Math.max(2, Math.trunc(count)));
}

export function classNameFor(scenario: JavaScenario): string {
  switch (scenario) {
    case "deadlock":
      return "DeadlockCycle";
    case "thread-pool-exhaustion":
      return "ThreadPoolExhaustion";
    case "sync-io-hotspot":
      return "SyncIoHotspot";
    case "dangerous-hot-lock":
      return "DangerousHotLock";
    default:
      return "LockContention";
  }
}

/**
 * Generate a runnable Java reproducer for a thread problem scenario.
 * Port of the former Rust/WASM `generateJava` (moved in feat-011 to shrink WASM).
 */
export function generateJava(scenario: JavaScenario, count: number): string {
  const n = normalizeCount(count);
  switch (scenario) {
    case "deadlock":
      return generateDeadlock(n);
    case "thread-pool-exhaustion":
      return generateThreadPoolExhaustion(n);
    case "sync-io-hotspot":
      return generateSyncIoHotspot(n);
    case "dangerous-hot-lock":
      return generateDangerousHotLock(n);
    default:
      return generateLockContention(n);
  }
}

function generateLockContention(workers: number): string {
  const nMinus1 = workers - 1;
  return `// Auto-generated by jblock: lock-contention reproducer.
// One thread holds LOCK forever; the other ${nMinus1} block waiting to enter it.
// Capture with: jstack <pid>  (or ThreadMXBean#dumpAllThreads)
public class LockContention {
    private static final Object LOCK = new Object();

    public static void main(String[] args) {
        final int workers = ${workers};
        for (int i = 0; i < workers; i++) {
            final int id = i;
            Thread t = new Thread(() -> {
                synchronized (LOCK) {
                    System.out.println("worker-" + id + " acquired LOCK");
                    // Hold the monitor so the remaining workers stay BLOCKED.
                    while (true) {
                        try {
                            Thread.sleep(Long.MAX_VALUE);
                        } catch (InterruptedException e) {
                            Thread.currentThread().interrupt();
                            return;
                        }
                    }
                }
            }, "worker-" + i);
            t.start();
        }
    }
}
`;
}

function generateDeadlock(threads: number): string {
  return `// Auto-generated by jblock: deadlock-cycle reproducer.
// ${threads} threads and ${threads} locks form a circular wait: thread i holds lock i and
// blocks acquiring lock (i+1) % ${threads}, closing a deadlock cycle.
// Capture with: jstack <pid>  (jstack also prints "Found one Java-level deadlock").
public class DeadlockCycle {
    public static void main(String[] args) {
        final int n = ${threads};
        final Object[] locks = new Object[n];
        for (int i = 0; i < n; i++) {
            locks[i] = new Object();
        }
        for (int i = 0; i < n; i++) {
            final int id = i;
            final Object first = locks[i];
            final Object second = locks[(i + 1) % n];
            Thread t = new Thread(() -> {
                synchronized (first) {
                    System.out.println("thread-" + id + " locked " + id);
                    try {
                        Thread.sleep(200);
                    } catch (InterruptedException e) {
                        Thread.currentThread().interrupt();
                        return;
                    }
                    synchronized (second) {
                        System.out.println("thread-" + id + " locked next");
                    }
                }
            }, "deadlock-" + i);
            t.start();
        }
    }
}
`;
}

function generateThreadPoolExhaustion(workers: number): string {
  return `// Auto-generated by jblock: thread-pool-exhaustion reproducer.
// A fixed pool of ${workers} workers all enter the same monitor; one holds it while
// sleeping and the rest stay BLOCKED — no idle getTask worker remains.
// Capture with: jstack <pid>
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class ThreadPoolExhaustion {
    private static final Object LOCK = new Object();

    public static void main(String[] args) throws Exception {
        final int workers = ${workers};
        final ExecutorService pool = Executors.newFixedThreadPool(workers);
        final CountDownLatch entered = new CountDownLatch(workers);
        for (int i = 0; i < workers; i++) {
            pool.submit(() -> {
                entered.countDown();
                synchronized (LOCK) {
                    try {
                        Thread.sleep(Long.MAX_VALUE);
                    } catch (InterruptedException e) {
                        Thread.currentThread().interrupt();
                    }
                }
            });
        }
        entered.await();
        // Keep the JVM alive so jstack can capture the stuck pool.
        Thread.sleep(Long.MAX_VALUE);
    }
}
`;
}

function generateSyncIoHotspot(clients: number): string {
  return `// Auto-generated by jblock: sync-io / RPC hotspot reproducer.
// A local server accepts connections but never writes; ${clients} client threads
// block forever in SocketInputStream.read — a classic synchronous I/O hotspot.
// Capture with: jstack <pid>
import java.io.InputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.concurrent.CountDownLatch;

public class SyncIoHotspot {
    public static void main(String[] args) throws Exception {
        final int clients = ${clients};
        final ServerSocket server = new ServerSocket(0);
        final int port = server.getLocalPort();

        Thread acceptor = new Thread(() -> {
            try {
                while (true) {
                    Socket peer = server.accept();
                    // Keep the accepted socket open without writing so clients stay blocked.
                    Thread.sleep(Long.MAX_VALUE);
                    peer.close();
                }
            } catch (Exception ignored) {
            }
        }, "io-acceptor");
        acceptor.setDaemon(true);
        acceptor.start();

        final CountDownLatch connected = new CountDownLatch(clients);
        for (int i = 0; i < clients; i++) {
            final int id = i;
            Thread t = new Thread(() -> {
                try {
                    Socket sock = new Socket("127.0.0.1", port);
                    connected.countDown();
                    InputStream in = sock.getInputStream();
                    // Block forever on a synchronous read (RPC-style stall).
                    while (in.read() >= 0) {
                        // no-op
                    }
                } catch (Exception ignored) {
                }
            }, "rpc-client-" + id);
            t.start();
        }
        connected.await();
        Thread.sleep(Long.MAX_VALUE);
    }
}
`;
}

function generateDangerousHotLock(threads: number): string {
  const waiters = Math.max(1, threads - 1);
  return `// Auto-generated by jblock: dangerous hot-lock owner reproducer.
// One owner holds LOCK while blocked in Thread.sleep; ${waiters} waiters stay BLOCKED.
// This is the "owner on blocking call" anti-pattern (feat-030).
// Capture with: jstack <pid>
import java.util.concurrent.CountDownLatch;

public class DangerousHotLock {
    private static final Object LOCK = new Object();

    public static void main(String[] args) throws Exception {
        final int waiters = ${waiters};
        final CountDownLatch ownerHolding = new CountDownLatch(1);
        final CountDownLatch waitersStarted = new CountDownLatch(waiters);

        Thread owner = new Thread(() -> {
            synchronized (LOCK) {
                ownerHolding.countDown();
                System.out.println("lock-owner holding LOCK while sleeping");
                try {
                    // Dangerous: blocking call while still holding the monitor.
                    Thread.sleep(Long.MAX_VALUE);
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                }
            }
        }, "lock-owner");
        owner.start();
        ownerHolding.await();

        for (int i = 0; i < waiters; i++) {
            final int id = i;
            Thread t = new Thread(() -> {
                waitersStarted.countDown();
                synchronized (LOCK) {
                    System.out.println("waiter-" + id + " acquired LOCK");
                }
            }, "waiter-" + i);
            t.start();
        }
        waitersStarted.await();
        // Brief pause so BLOCKED waiters show up in jstack.
        Thread.sleep(300);
        Thread.sleep(Long.MAX_VALUE);
    }
}
`;
}
