//! Generate small, runnable Java programs that reproduce common thread problems.
//!
//! Originally feat-007 (also exposed to the browser via WASM). feat-011 moved the
//! page-facing generator to `web/src/codegen.ts` so this module is compiled only
//! for host tests and the `gen_java` example — keeping it out of the WASM binary.

/// A reproducible thread-problem scenario.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Scenario {
    /// One holder + N-1 threads blocked waiting to lock the same monitor.
    LockContention,
    /// N threads in a circular wait (classic deadlock cycle).
    Deadlock,
    /// Fixed thread pool of N workers all stuck holding/waiting on one lock (feat-028).
    ThreadPoolExhaustion,
    /// N client threads blocked in synchronous socket reads (feat-029).
    SyncIoHotspot,
    /// Owner holds a monitor while blocked (sleep/I/O); waiters pile up (feat-030).
    DangerousHotLock,
    /// Threads blocked borrowing from an exhausted connection pool (feat-031).
    ConnectionPoolStarve,
    /// Circular Future.get / CountDownLatch.await wait tree (feat-032).
    FutureLatchDeadlock,
    /// Contended Log4j/Logback-style appender lock (feat-033).
    LoggingAppenderContention,
}

impl Scenario {
    /// The generated Java public class name (also the file name stem).
    pub fn class_name(self) -> &'static str {
        match self {
            Scenario::LockContention => "LockContention",
            Scenario::Deadlock => "DeadlockCycle",
            Scenario::ThreadPoolExhaustion => "ThreadPoolExhaustion",
            Scenario::SyncIoHotspot => "SyncIoHotspot",
            Scenario::DangerousHotLock => "DangerousHotLock",
            Scenario::ConnectionPoolStarve => "ConnectionPoolStarve",
            Scenario::FutureLatchDeadlock => "FutureLatchDeadlock",
            Scenario::LoggingAppenderContention => "LoggingAppenderContention",
        }
    }
}

/// Parse a scenario name coming from the CLI/tests. Accepts a few aliases.
pub fn parse_scenario(name: &str) -> Option<Scenario> {
    match name.trim().to_ascii_lowercase().replace('_', "-").as_str() {
        "lock-contention" | "contention" | "waiting" | "waiting-threads" => {
            Some(Scenario::LockContention)
        }
        "deadlock" | "deadlock-cycle" | "cycle" => Some(Scenario::Deadlock),
        "thread-pool-exhaustion" | "pool-exhaustion" | "thread-pool" | "pool" => {
            Some(Scenario::ThreadPoolExhaustion)
        }
        "sync-io-hotspot" | "sync-io" | "io-hotspot" | "rpc-hotspot" | "socket-hotspot" => {
            Some(Scenario::SyncIoHotspot)
        }
        "dangerous-hot-lock" | "hot-lock-owner" | "dangerous-lock" | "blocking-owner" => {
            Some(Scenario::DangerousHotLock)
        }
        "connection-pool-starve"
        | "connection-pool"
        | "conn-pool"
        | "hikari-starve"
        | "borrow-block" => Some(Scenario::ConnectionPoolStarve),
        "future-latch-deadlock"
        | "future-latch"
        | "latch-deadlock"
        | "future-get"
        | "countdown-latch" => Some(Scenario::FutureLatchDeadlock),
        "logging-appender-contention"
        | "logging-contention"
        | "log-appender"
        | "logback-contention"
        | "log4j-contention" => Some(Scenario::LoggingAppenderContention),
        _ => None,
    }
}

/// Clamp the requested thread/worker count into a sane range (>= 2).
fn normalize_count(count: usize) -> usize {
    count.clamp(2, 64)
}

/// Generate Java source for the given scenario and thread count.
pub fn generate(scenario: Scenario, count: usize) -> String {
    let n = normalize_count(count);
    match scenario {
        Scenario::LockContention => generate_lock_contention(n),
        Scenario::Deadlock => generate_deadlock(n),
        Scenario::ThreadPoolExhaustion => generate_thread_pool_exhaustion(n),
        Scenario::SyncIoHotspot => generate_sync_io_hotspot(n),
        Scenario::DangerousHotLock => generate_dangerous_hot_lock(n),
        Scenario::ConnectionPoolStarve => generate_connection_pool_starve(n),
        Scenario::FutureLatchDeadlock => generate_future_latch_deadlock(n),
        Scenario::LoggingAppenderContention => generate_logging_appender_contention(n),
    }
}

fn generate_lock_contention(workers: usize) -> String {
    format!(
        r#"// Auto-generated by jblock: lock-contention reproducer.
// One thread holds LOCK forever; the other {n_minus_1} block waiting to enter it.
// Capture with: jstack <pid>  (or ThreadMXBean#dumpAllThreads)
public class LockContention {{
    private static final Object LOCK = new Object();

    public static void main(String[] args) {{
        final int workers = {workers};
        for (int i = 0; i < workers; i++) {{
            final int id = i;
            Thread t = new Thread(() -> {{
                synchronized (LOCK) {{
                    System.out.println("worker-" + id + " acquired LOCK");
                    // Hold the monitor so the remaining workers stay BLOCKED.
                    while (true) {{
                        try {{
                            Thread.sleep(Long.MAX_VALUE);
                        }} catch (InterruptedException e) {{
                            Thread.currentThread().interrupt();
                            return;
                        }}
                    }}
                }}
            }}, "worker-" + i);
            t.start();
        }}
    }}
}}
"#,
        workers = workers,
        n_minus_1 = workers - 1
    )
}

fn generate_deadlock(threads: usize) -> String {
    format!(
        r#"// Auto-generated by jblock: deadlock-cycle reproducer.
// {n} threads and {n} locks form a circular wait: thread i holds lock i and
// blocks acquiring lock (i+1) % {n}, closing a deadlock cycle.
// Capture with: jstack <pid>  (jstack also prints "Found one Java-level deadlock").
public class DeadlockCycle {{
    public static void main(String[] args) {{
        final int n = {threads};
        final Object[] locks = new Object[n];
        for (int i = 0; i < n; i++) {{
            locks[i] = new Object();
        }}
        for (int i = 0; i < n; i++) {{
            final int id = i;
            final Object first = locks[i];
            final Object second = locks[(i + 1) % n];
            Thread t = new Thread(() -> {{
                synchronized (first) {{
                    System.out.println("thread-" + id + " locked " + id);
                    try {{
                        Thread.sleep(200);
                    }} catch (InterruptedException e) {{
                        Thread.currentThread().interrupt();
                        return;
                    }}
                    synchronized (second) {{
                        System.out.println("thread-" + id + " locked next");
                    }}
                }}
            }}, "deadlock-" + i);
            t.start();
        }}
    }}
}}
"#,
        threads = threads,
        n = threads
    )
}

fn generate_thread_pool_exhaustion(workers: usize) -> String {
    format!(
        r#"// Auto-generated by jblock: thread-pool-exhaustion reproducer.
// A fixed pool of {workers} workers all enter the same monitor; one holds it while
// sleeping and the rest stay BLOCKED — no idle getTask worker remains.
// Capture with: jstack <pid>
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class ThreadPoolExhaustion {{
    private static final Object LOCK = new Object();

    public static void main(String[] args) throws Exception {{
        final int workers = {workers};
        final ExecutorService pool = Executors.newFixedThreadPool(workers);
        final CountDownLatch entered = new CountDownLatch(workers);
        for (int i = 0; i < workers; i++) {{
            pool.submit(() -> {{
                entered.countDown();
                synchronized (LOCK) {{
                    try {{
                        Thread.sleep(Long.MAX_VALUE);
                    }} catch (InterruptedException e) {{
                        Thread.currentThread().interrupt();
                    }}
                }}
            }});
        }}
        entered.await();
        // Keep the JVM alive so jstack can capture the stuck pool.
        Thread.sleep(Long.MAX_VALUE);
    }}
}}
"#,
        workers = workers
    )
}

fn generate_sync_io_hotspot(clients: usize) -> String {
    format!(
        r#"// Auto-generated by jblock: sync-io / RPC hotspot reproducer.
// A local server accepts connections but never writes; {clients} client threads
// block forever in SocketInputStream.read — a classic synchronous I/O hotspot.
// Capture with: jstack <pid>
import java.io.InputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.concurrent.CountDownLatch;

public class SyncIoHotspot {{
    public static void main(String[] args) throws Exception {{
        final int clients = {clients};
        final ServerSocket server = new ServerSocket(0);
        final int port = server.getLocalPort();

        Thread acceptor = new Thread(() -> {{
            try {{
                while (true) {{
                    Socket peer = server.accept();
                    // Keep the accepted socket open without writing so clients stay blocked.
                    Thread.sleep(Long.MAX_VALUE);
                    peer.close();
                }}
            }} catch (Exception ignored) {{
            }}
        }}, "io-acceptor");
        acceptor.setDaemon(true);
        acceptor.start();

        final CountDownLatch connected = new CountDownLatch(clients);
        for (int i = 0; i < clients; i++) {{
            final int id = i;
            Thread t = new Thread(() -> {{
                try {{
                    Socket sock = new Socket("127.0.0.1", port);
                    connected.countDown();
                    InputStream in = sock.getInputStream();
                    // Block forever on a synchronous read (RPC-style stall).
                    while (in.read() >= 0) {{
                        // no-op
                    }}
                }} catch (Exception ignored) {{
                }}
            }}, "rpc-client-" + id);
            t.start();
        }}
        connected.await();
        Thread.sleep(Long.MAX_VALUE);
    }}
}}
"#,
        clients = clients
    )
}

fn generate_dangerous_hot_lock(threads: usize) -> String {
    // threads = 1 owner + (n-1) waiters; normalize_count already ensures >= 2.
    let waiters = threads - 1;
    format!(
        r#"// Auto-generated by jblock: dangerous hot-lock owner reproducer.
// One owner holds LOCK while blocked in Thread.sleep; {waiters} waiters stay BLOCKED.
// This is the "owner on blocking call" anti-pattern (feat-030).
// Capture with: jstack <pid>
import java.util.concurrent.CountDownLatch;

public class DangerousHotLock {{
    private static final Object LOCK = new Object();

    public static void main(String[] args) throws Exception {{
        final int waiters = {waiters};
        final CountDownLatch ownerHolding = new CountDownLatch(1);
        final CountDownLatch waitersStarted = new CountDownLatch(waiters);

        Thread owner = new Thread(() -> {{
            synchronized (LOCK) {{
                ownerHolding.countDown();
                System.out.println("lock-owner holding LOCK while sleeping");
                try {{
                    // Dangerous: blocking call while still holding the monitor.
                    Thread.sleep(Long.MAX_VALUE);
                }} catch (InterruptedException e) {{
                    Thread.currentThread().interrupt();
                }}
            }}
        }}, "lock-owner");
        owner.start();
        ownerHolding.await();

        for (int i = 0; i < waiters; i++) {{
            final int id = i;
            Thread t = new Thread(() -> {{
                waitersStarted.countDown();
                synchronized (LOCK) {{
                    System.out.println("waiter-" + id + " acquired LOCK");
                }}
            }}, "waiter-" + i);
            t.start();
        }}
        waitersStarted.await();
        // Brief pause so BLOCKED waiters show up in jstack.
        Thread.sleep(300);
        Thread.sleep(Long.MAX_VALUE);
    }}
}}
"#,
        waiters = waiters
    )
}

fn generate_connection_pool_starve(borrowers: usize) -> String {
    // 1 holder keeps the only connection; remaining threads block in getConnection/borrowObject.
    let waiters = borrowers.saturating_sub(1).max(1);
    format!(
        r#"// Auto-generated by jblock: connection-pool borrow blocking reproducer.
// A tiny pool of size 1 is held forever; {waiters} callers block in getConnection()/borrowObject()
// with stack frames that mirror Hikari/DBCP-style borrow waits (feat-031).
// Capture with: jstack <pid>
import java.util.concurrent.CountDownLatch;

public class ConnectionPoolStarve {{
    /** Minimal stand-in for HikariDataSource / BasicDataSource. */
    static final class HikariDataSource {{
        private int available = 1;

        public synchronized Object getConnection() throws InterruptedException {{
            return borrowObject();
        }}

        public synchronized Object borrowObject() throws InterruptedException {{
            while (available == 0) {{
                wait();
            }}
            available--;
            return new Object();
        }}

        public synchronized void release(Object ignored) {{
            available++;
            notifyAll();
        }}
    }}

    public static void main(String[] args) throws Exception {{
        final int waiters = {waiters};
        final HikariDataSource pool = new HikariDataSource();
        final CountDownLatch held = new CountDownLatch(1);
        final CountDownLatch waiting = new CountDownLatch(waiters);

        Thread holder = new Thread(() -> {{
            try {{
                Object conn = pool.getConnection();
                held.countDown();
                System.out.println("pool-holder borrowed the only connection");
                Thread.sleep(Long.MAX_VALUE);
                pool.release(conn);
            }} catch (InterruptedException e) {{
                Thread.currentThread().interrupt();
            }}
        }}, "pool-holder");
        holder.start();
        held.await();

        for (int i = 0; i < waiters; i++) {{
            final int id = i;
            Thread t = new Thread(() -> {{
                try {{
                    waiting.countDown();
                    Object conn = pool.getConnection();
                    System.out.println("db-borrower-" + id + " got connection");
                    pool.release(conn);
                }} catch (InterruptedException e) {{
                    Thread.currentThread().interrupt();
                }}
            }}, "db-borrower-" + i);
            t.start();
        }}
        waiting.await();
        Thread.sleep(400);
        Thread.sleep(Long.MAX_VALUE);
    }}
}}
"#,
        waiters = waiters
    )
}

fn generate_future_latch_deadlock(threads: usize) -> String {
    // Circular CompletableFuture.get() wait plus a CountDownLatch cross-await pair
    // so live dumps exercise both Future.get and CountDownLatch.await frames.
    let future_waiters = threads;
    format!(
        r#"// Auto-generated by jblock: Future/Latch wait-tree reproducer.
// {future_waiters} threads form a circular CompletableFuture.get() wait (logical deadlock),
// plus two threads in a CountDownLatch cross-await (feat-032).
// Capture with: jstack <pid>
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CountDownLatch;

public class FutureLatchDeadlock {{
    @SuppressWarnings("unchecked")
    public static void main(String[] args) throws Exception {{
        final int futureWaiters = {future_waiters};
        final CompletableFuture<Void>[] futures = new CompletableFuture[futureWaiters];
        for (int i = 0; i < futureWaiters; i++) {{
            futures[i] = new CompletableFuture<>();
        }}
        final CountDownLatch started = new CountDownLatch(futureWaiters);

        for (int i = 0; i < futureWaiters; i++) {{
            final int id = i;
            Thread t = new Thread(() -> {{
                try {{
                    started.countDown();
                    System.out.println("future-waiter-" + id + " waiting on future-" + ((id + 1) % futureWaiters));
                    // Logical deadlock: each waits for the next future in the ring.
                    futures[(id + 1) % futureWaiters].get();
                    futures[id].complete(null);
                }} catch (Exception e) {{
                    Thread.currentThread().interrupt();
                }}
            }}, "future-waiter-" + i);
            t.start();
        }}
        started.await();

        final CountDownLatch latchA = new CountDownLatch(1);
        final CountDownLatch latchB = new CountDownLatch(1);
        Thread latch0 = new Thread(() -> {{
            try {{
                System.out.println("latch-waiter-0 awaiting latchB");
                latchB.await();
                latchA.countDown();
            }} catch (InterruptedException e) {{
                Thread.currentThread().interrupt();
            }}
        }}, "latch-waiter-0");
        Thread latch1 = new Thread(() -> {{
            try {{
                System.out.println("latch-waiter-1 awaiting latchA");
                latchA.await();
                latchB.countDown();
            }} catch (InterruptedException e) {{
                Thread.currentThread().interrupt();
            }}
        }}, "latch-waiter-1");
        latch0.start();
        latch1.start();

        Thread.sleep(400);
        Thread.sleep(Long.MAX_VALUE);
    }}
}}
"#,
        future_waiters = future_waiters
    )
}

fn generate_logging_appender_contention(threads: usize) -> String {
    // 1 holder keeps the appender lock in a slow append; remaining threads BLOCKED.
    let waiters = threads.saturating_sub(1).max(1);
    format!(
        r#"// Auto-generated by jblock: logging-appender contention reproducer.
// One thread holds a synchronized OutputStreamAppender.append() (Logback/Log4j style);
// {waiters} other loggers stay BLOCKED on the same appender lock (feat-033).
// Capture with: jstack <pid>
import java.util.concurrent.CountDownLatch;

public class LoggingAppenderContention {{
    /** Minimal stand-in for Logback OutputStreamAppender / Log4j AbstractAppender. */
    static final class OutputStreamAppender {{
        private final CountDownLatch entered;

        OutputStreamAppender(CountDownLatch entered) {{
            this.entered = entered;
        }}

        public synchronized void append(String event) {{
            entered.countDown();
            try {{
                // Slow append while holding the appender monitor (classic logging bottleneck).
                Thread.sleep(Long.MAX_VALUE);
            }} catch (InterruptedException e) {{
                Thread.currentThread().interrupt();
            }}
        }}

        public void doAppend(String event) {{
            append(event);
        }}
    }}

    static final class Logger {{
        private final OutputStreamAppender appender;

        Logger(CountDownLatch entered) {{
            this.appender = new OutputStreamAppender(entered);
        }}

        public void info(String msg) {{
            appender.doAppend(msg);
        }}
    }}

    public static void main(String[] args) throws Exception {{
        final int waiters = {waiters};
        final CountDownLatch holding = new CountDownLatch(1);
        final CountDownLatch waiting = new CountDownLatch(waiters);
        final Logger log = new Logger(holding);

        Thread holder = new Thread(() -> {{
            System.out.println("log-holder entering append()");
            log.info("slow-append");
        }}, "log-holder");
        holder.start();
        holding.await();

        for (int i = 0; i < waiters; i++) {{
            final int id = i;
            Thread t = new Thread(() -> {{
                waiting.countDown();
                System.out.println("log-writer-" + id + " calling info()");
                log.info("blocked-append-" + id);
            }}, "log-writer-" + i);
            t.start();
        }}
        waiting.await();
        Thread.sleep(400);
        Thread.sleep(Long.MAX_VALUE);
    }}
}}
"#,
        waiters = waiters
    )
}

#[cfg(test)]
#[path = "tests/java_code_generation.rs"]
mod java_code_generation;
